package views;

import domain.Marca;
import domain.Sucursal;
import domain.Vehiculo;
import domain.VehiculoCombustible;
import domain.VehiculoElectrico;
import domain.VehiculoTipo;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class RegistrarVehiculoView extends javax.swing.JFrame {

    /**
     * Creates new form RefistrarVehiculo
     */
    public RegistrarVehiculoView() {
        initComponents();
        llenarCmbBoxs();
        limpiarCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPatente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCapacidadDeCarga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblAutonomia = new javax.swing.JLabel();
        txtAutonomia = new javax.swing.JTextField();
        txtLitrosExtra = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        cmbMarcas = new javax.swing.JComboBox();
        cmbTipo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        cmbSucursales = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Patente");

        jLabel8.setText("Marca");

        jLabel9.setText("Modelo:");

        jLabel10.setText("Tipo:");

        txtCapacidadDeCarga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCapacidadDeCargaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCapacidadDeCargaFocusLost(evt);
            }
        });
        txtCapacidadDeCarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCapacidadDeCargaKeyTyped(evt);
            }
        });

        jLabel11.setText("Cap. de carga (Kg):");

        lblAutonomia.setText("Autonomia (Km/L):");

        txtAutonomia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAutonomiaKeyTyped(evt);
            }
        });

        txtLitrosExtra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLitrosExtraKeyTyped(evt);
            }
        });

        jLabel13.setText("Litros extras (Litros):");

        jLabel14.setText("Año:");

        txtAnio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAnioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAnioFocusLost(evt);
            }
        });
        txtAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnioKeyTyped(evt);
            }
        });

        cmbMarcas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar Vehiculo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbSucursales.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSucursalesActionPerformed(evt);
            }
        });

        jLabel15.setText("Sucuusal");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cargar Vehiculo");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPatente)
                            .addComponent(cmbMarcas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtModelo)
                            .addComponent(txtAnio)
                            .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLitrosExtra)
                                    .addComponent(txtAutonomia)
                                    .addComponent(txtCapacidadDeCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(237, 237, 237)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCapacidadDeCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLitrosExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed

        this.validarTxtField();
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void txtAutonomiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAutonomiaKeyTyped
        validarNumeroDecimal(evt, txtAutonomia);
    }//GEN-LAST:event_txtAutonomiaKeyTyped

    private void txtLitrosExtraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLitrosExtraKeyTyped
        validarNumeroDecimal(evt, txtLitrosExtra);
    }//GEN-LAST:event_txtLitrosExtraKeyTyped

    private void txtAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnioKeyTyped
        validarNumeroEntero(evt);
    }//GEN-LAST:event_txtAnioKeyTyped

    private void txtCapacidadDeCargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapacidadDeCargaKeyTyped
        validarNumeroDecimal(evt, txtCapacidadDeCarga);
    }//GEN-LAST:event_txtCapacidadDeCargaKeyTyped

    private void cmbSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSucursalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSucursalesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!validarEntradas()) {
            return;
        }
        Vehiculo vehiculo = instanciarVehiculo();
        if (vehiculo == null) {
            JOptionPane.showMessageDialog(null, "Hubo un error al intentar guardar el vehiculo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Controlador.guardarVehiculo(vehiculo);
        JOptionPane.showMessageDialog(null, "Vehiculo Guardado", "Succes", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        ListarVehiculosView lista = new ListarVehiculosView();
        lista.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtAnioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnioFocusGained
        if (txtAnio.getText().equals("0")) {
            txtAnio.setText("");
        }
    }//GEN-LAST:event_txtAnioFocusGained

    private void txtAnioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnioFocusLost
        if (txtAnio.getText().equals("")) {
            txtAnio.setText("0");
        }
    }//GEN-LAST:event_txtAnioFocusLost

    private void txtCapacidadDeCargaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCapacidadDeCargaFocusGained
        if (txtCapacidadDeCarga.getText().equals("0")) {
            txtCapacidadDeCarga.setText("");
        }
    }//GEN-LAST:event_txtCapacidadDeCargaFocusGained

    private void txtCapacidadDeCargaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCapacidadDeCargaFocusLost
        if (txtCapacidadDeCarga.getText().equals("")) {
            txtCapacidadDeCarga.setText("0");
        }
    }//GEN-LAST:event_txtCapacidadDeCargaFocusLost

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarVehiculoView().setVisible(true);
            }
        });
    }

    public void llenarCmbBoxs() {

        DefaultComboBoxModel<Marca> marcas = new DefaultComboBoxModel<>();
        for (Marca marca : Controlador.getMarcas()) {
            marcas.addElement(marca);
        }

        cmbMarcas.setModel(marcas);
        cmbMarcas.setSelectedIndex(-1);

        DefaultComboBoxModel<Sucursal> sucursales = new DefaultComboBoxModel<>();
        for (Sucursal sucursal : Controlador.getSucursales()) {
            sucursales.addElement(sucursal);
        }

        cmbSucursales.setModel(sucursales);
        cmbSucursales.setSelectedIndex(-1);

        DefaultComboBoxModel<VehiculoTipo> tipoVehiculo = new DefaultComboBoxModel<>(VehiculoTipo.values());
        cmbTipo.setModel(tipoVehiculo);
        cmbTipo.setSelectedIndex(-1);

    }

    public void validarTxtField() {
        if (cmbTipo.getSelectedItem() == null) {
            txtAutonomia.setEnabled(false);
            txtLitrosExtra.setEnabled(false);
            lblAutonomia.setText("Autonomia:");

            return;
        }
        if (((VehiculoTipo) cmbTipo.getSelectedItem()).equals(VehiculoTipo.ELECTRICO)) {
            txtAutonomia.setEnabled(false);
            txtAutonomia.setText("16.0");
            txtLitrosExtra.setEnabled(false);
            txtLitrosExtra.setText("0");
            lblAutonomia.setText("Autonomia (Kw/H):");
        }
        if (((VehiculoTipo) cmbTipo.getSelectedItem()).equals(VehiculoTipo.COMBUSTIBLE)) {
            txtAutonomia.setEnabled(true);
            txtAutonomia.setText("0");
            txtLitrosExtra.setEnabled(true);
            txtLitrosExtra.setText("0");
            lblAutonomia.setText("Autonomia (Km/L):");
        }

    }

    private void validarNumeroEntero(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }

    private void validarNumeroDecimal(java.awt.event.KeyEvent evt, javax.swing.JTextField field) {
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && c != '.') {
            evt.consume();
        }

        // evitar más de un punto
        if (c == '.' && field.getText().contains(".")) {
            evt.consume();
        }
    }

    public boolean validarEntradas() {

        if (cmbMarcas.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Error: Debe indicar una marca", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (cmbSucursales.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Error: Debe indicar una sucursal", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (cmbTipo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Error: Debe indicar el tipo de vehiculo", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        try {
            double autonomia = (double) Double.parseDouble(txtAutonomia.getText());
            double capacidadCarga = (double) Double.parseDouble(txtCapacidadDeCarga.getText());
            double litrosExtra = (double) Double.parseDouble(txtLitrosExtra.getText());
            int anio = Integer.parseInt(txtAnio.getText());

            if (anio < 2000 || anio > java.time.Year.now().getValue()) {
                JOptionPane.showMessageDialog(null, "Error: Debe ingresar un año entre 2000 y el actual", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }

            if (litrosExtra <= 0 && (java.time.Year.now().getValue() - anio) < 5 && ((VehiculoTipo) cmbTipo.getSelectedItem()).equals(VehiculoTipo.COMBUSTIBLE)) {
                JOptionPane.showMessageDialog(null, "Debe ingresar litros extra para este vehiculo", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }

            if (txtPatente.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Error: Debe ingresar la patente del vehiculo", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }

            if (txtModelo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Error: Debe ingresar el modelo del vehiculo", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (!(capacidadCarga > 0)) {
                JOptionPane.showMessageDialog(null, "Error: Capacidad de carga invalida", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (!(autonomia > 0)) {
                JOptionPane.showMessageDialog(null, "Error: Autonomia invalida", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }

        } catch (Error e) {
            JOptionPane.showMessageDialog(null, "Error: No pudo parsear", "Error", JOptionPane.ERROR_MESSAGE);
        }

        return true;

    }

    private Vehiculo instanciarVehiculo() {
        Vehiculo vehiculo = null;

        if (((VehiculoTipo) cmbTipo.getSelectedItem()).equals(VehiculoTipo.COMBUSTIBLE)) {
            vehiculo = new VehiculoCombustible(
                    txtPatente.getText(),
                    (Marca) cmbMarcas.getSelectedItem(),
                    txtModelo.getText(),
                    Integer.parseInt(txtAnio.getText()),
                    Double.parseDouble(txtCapacidadDeCarga.getText()),
                    (Sucursal) cmbSucursales.getSelectedItem(),
                    Double.parseDouble(txtAutonomia.getText()),
                    Double.parseDouble(txtLitrosExtra.getText()));
            System.out.println("combustible");

        }
        if (((VehiculoTipo) cmbTipo.getSelectedItem()).equals(VehiculoTipo.ELECTRICO)) {
            vehiculo = new VehiculoElectrico(
                    txtPatente.getText(),
                    (Marca) cmbMarcas.getSelectedItem(),
                    txtModelo.getText(),
                    Integer.parseInt(txtAnio.getText()),
                    Double.parseDouble(txtCapacidadDeCarga.getText()),
                    (Sucursal) cmbSucursales.getSelectedItem(),
                    Double.parseDouble(txtAutonomia.getText()));
            System.out.println("ELECTRICO");

        }
        return vehiculo;
    }

    private void limpiarCampos() {
        cmbMarcas.setSelectedIndex(-1);
        cmbSucursales.setSelectedIndex(-1);
        cmbTipo.setSelectedIndex(-1);
        txtAnio.setText("0");
        txtAutonomia.setText("0");
        txtCapacidadDeCarga.setText("0");
        txtLitrosExtra.setText("0");
        txtModelo.setText("");
        txtAnio.setText("0");
        txtPatente.setText("");
        lblAutonomia.setText("Autonomia");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbMarcas;
    private javax.swing.JComboBox cmbSucursales;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAutonomia;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAutonomia;
    private javax.swing.JTextField txtCapacidadDeCarga;
    private javax.swing.JTextField txtLitrosExtra;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPatente;
    // End of variables declaration//GEN-END:variables
}
